const contacts = [
  {
    id: 1,
    name: "Agus Mulyono",
    email: "agus@example.com",
    phone: "081234567890",
    address: null,
    birthday: null,
    company: "Example Inc.",
    jobTitle: "Software Engineer",
    websiteUrl: "https://example.com",
  },
  {
    id: 2,
    name: "Dana Agung",
    email: "dana@exammple.com",
    phone: "081234567891",
    address: "Jl. Babakan blok kasab",
    birthday: null,
    company: "Example Inc.",
    jobTitle: "Software Engineer",
    websiteUrl: "https://example.com",
  },
  {
    id: 3,
    name: "Bowo MBG",
    email: "bowo@example.com",
    phone: "081234567892",
    address: "Jl. in aja",
    birthday: "1990-01-01",
    company: "Example Inc.",
    jobTitle: "Software Engineer",
    websiteUrl: "https://example.com",
  },
  {
    id: 4,
    name: "Ariel Tatum",
    email: "tatum@example.com",
    phone: "081234567893",
    address: "Jl. in aja",
    birthday: "1990-01-01",
    company: "Example Inc.",
    jobTitle: "Software Engineer",
    websiteUrl: "https://example.com",
  },
];

console.log(contacts);
